-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
NOME VARCHAR(10),
CPF VARCHAR(10),
TELEFONE VARCHAR(10),
ENDERECO VARCHAR(10),
SEXO VARCHAR(10),
EMAIL VARCHAR(10)
)

